-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 14:52:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dsw1_reserva_hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dsw1_reserva_hotel` ;

-- -----------------------------------------------------
-- Schema dsw1_reserva_hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dsw1_reserva_hotel` DEFAULT CHARACTER SET utf8 ;
USE `dsw1_reserva_hotel` ;

-- -----------------------------------------------------
-- Table `dsw1_reserva_hotel`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsw1_reserva_hotel`.`hotel` ;

CREATE TABLE IF NOT EXISTS `dsw1_reserva_hotel`.`hotel` (
  `cnpj` VARCHAR(14) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NOT NULL,
  `daily_rate` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dsw1_reserva_hotel`.`booking_site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsw1_reserva_hotel`.`booking_site` ;

CREATE TABLE IF NOT EXISTS `dsw1_reserva_hotel`.`booking_site` (
  `url` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dsw1_reserva_hotel`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsw1_reserva_hotel`.`user` ;

CREATE TABLE IF NOT EXISTS `dsw1_reserva_hotel`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `hotel_cnpj` VARCHAR(14) NULL,
  `booking_site_url` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_hotel1_idx` (`hotel_cnpj` ASC) VISIBLE,
  INDEX `fk_user_booking_site1_idx` (`booking_site_url` ASC) VISIBLE,
  CONSTRAINT `fk_user_hotel1`
    FOREIGN KEY (`hotel_cnpj`)
    REFERENCES `dsw1_reserva_hotel`.`hotel` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_booking_site1`
    FOREIGN KEY (`booking_site_url`)
    REFERENCES `dsw1_reserva_hotel`.`booking_site` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dsw1_reserva_hotel`.`sale_off`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dsw1_reserva_hotel`.`sale_off` ;

CREATE TABLE IF NOT EXISTS `dsw1_reserva_hotel`.`sale_off` (
  `hotel_cnpj` VARCHAR(14) NOT NULL,
  `booking_site_url` VARCHAR(45) NOT NULL,
  `initial_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `discount` DECIMAL(3,1) NOT NULL,
  PRIMARY KEY (`hotel_cnpj`, `booking_site_url`, `initial_date`, `final_date`),
  INDEX `fk_hotel_has_booking_site_booking_site1_idx` (`booking_site_url` ASC) VISIBLE,
  INDEX `fk_hotel_has_booking_site_hotel_idx` (`hotel_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_has_booking_site_hotel`
    FOREIGN KEY (`hotel_cnpj`)
    REFERENCES `dsw1_reserva_hotel`.`hotel` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_has_booking_site_booking_site1`
    FOREIGN KEY (`booking_site_url`)
    REFERENCES `dsw1_reserva_hotel`.`booking_site` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `user`(email, password,hotel_cnpj, booking_site_url) VALUES ('admin','admin', null, null);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
