-- MySQL Script generated by MySQL Workbench
-- Wed Nov 25 21:24:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`hotel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`hotel` (
  `cnpj` INT NOT NULL,
  `nome_do_hotel` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `diaria` decimal(5,2) NOT NULL,
  PRIMARY KEY (`cnpj`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`site_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`site_reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`site_reserva` (
  `url` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`url`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `email` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promocao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`promocao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`promocao` (
  `hotel_cnpj` INT NOT NULL,
  `site_reserva_url` VARCHAR(60) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `desconto` INT NOT NULL,
  PRIMARY KEY (`hotel_cnpj`, `site_reserva_url`, `data_inicio`, `data_fim`),
  INDEX `fk_hotel_has_site_reserva_site_reserva1_idx` (`site_reserva_url` ASC) VISIBLE,
  INDEX `fk_hotel_has_site_reserva_hotel_idx` (`hotel_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_hotel_has_site_reserva_hotel`
    FOREIGN KEY (`hotel_cnpj`)
    REFERENCES `mydb`.`hotel` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hotel_has_site_reserva_site_reserva1`
    FOREIGN KEY (`site_reserva_url`)
    REFERENCES `mydb`.`site_reserva` (`url`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;